{\rtf1\ansi\ansicpg1252\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 name: macOS CI\
\
on:\
  schedule:\
    - cron: "0 6 * * *"\
  push:\
  pull_request:\
\
jobs:\
  ci-tests:\
    runs-on: macos-latest\
    strategy:\
      matrix:\
        python-version: ["3.7", "3.8", "3.9", "3.10"]\
    name: macOS CI\
    steps:\
      - name: Check out source repository\
        uses: actions/checkout@v3\
      - name: Set up Python $\{\{ matrix.python-version \}\} environment\
        uses: actions/setup-python@v2\
        with:\
          python-version: $\{\{ matrix.python-version \}\}\
      - name: Python environment report\
        run: python -c "import sys; print(sys.version)"\
      - name: Run $\{\{ matrix.python-version \}\} platform tests (default)\
        uses: py-actions/flake8@master\
        with:\
          path: "tests/test-default.py" # have to restrict because there are other tests with flake8 fails\
      - name: Run $\{\{ matrix.python-version \}\} platform tests (with args)\
        uses: py-actions/flake8@master\
        with:\
          update-pip: "true"\
          ignore: "F401"\
          exclude: "tests/test.py"\
          max-line-length: "100"\
          args: "--quiet"\
          path: "tests/test-args.py"\
          flake8-version: "main"\
          plugins: "flake8-bugbear==22.1.11 flake8-black"}